# Generated by Django 3.2.2 on 2021-05-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210423_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='user',
            name='patient',
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
