# Generated by Django 3.2.2 on 2021-05-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='labAssitant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='radiologist',
            field=models.BooleanField(default=False),
        ),
    ]
