# Generated by Django 3.2.2 on 2021-05-08 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DoctorModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('respiratory', models.CharField(max_length=50, null=True)),
                ('medicines', models.TextField()),
                ('allergies', models.CharField(max_length=50, null=True)),
                ('doc_pat_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorModule.doctorpatientrelation')),
            ],
        ),
    ]
