# Generated by Django 3.2.2 on 2021-05-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, null=True)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('dateAdmitted', models.DateTimeField(auto_now_add=True)),
                ('criticallity', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
