# Generated by Django 3.2.2 on 2021-05-08 06:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetails',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='lastname',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='adhaar',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='bystander_mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='personal_mobile_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
