# Generated by Django 3.2.2 on 2021-05-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0002_auto_20210508_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='bystander_mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='personal_mobile_no',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
