# Generated by Django 3.2.2 on 2021-05-08 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0003_auto_20210508_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='dateAdmitted',
            field=models.DateTimeField(null=True),
        ),
    ]
