# Generated by Django 3.2.2 on 2021-05-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0004_alter_patientdetails_dateadmitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='RT_PCR_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swab_taken', models.BooleanField(null=True)),
                ('hrct_taken', models.BooleanField(null=True)),
                ('positive_or_negative', models.BooleanField(null=True)),
                ('sr_id', models.CharField(max_length=50, null=True)),
                ('icmr_id', models.CharField(max_length=50, null=True)),
                ('ct_thorax_taken', models.BooleanField(null=True)),
                ('ct_thorax_date', models.DateField(null=True)),
            ],
        ),
    ]
