# Generated by Django 3.2.2 on 2021-05-08 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PatientModule', '0005_rt_pcr_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='doctor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rt_pcr_details',
            name='date_of_test',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rt_pcr_details',
            name='lab_name_with_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rt_pcr_details',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PatientModule.patientdetails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rt_pcr_details',
            name='ct_thorax_taken',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rt_pcr_details',
            name='hrct_taken',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='rt_pcr_details',
            name='positive_or_negative',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rt_pcr_details',
            name='swab_taken',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
