# Generated by Django 3.2.2 on 2021-05-08 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0007_auto_20210508_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='ct_thorax_date',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='ct_thorax_taken',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='date_of_test',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='hrct_taken',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='icmr_id',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='lab_name_with_address',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='positive_or_negative',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='sr_id',
        ),
        migrations.RemoveField(
            model_name='patientdetails',
            name='swab_taken',
        ),
        migrations.CreateModel(
            name='RT_PCR_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swab_taken', models.CharField(max_length=3, null=True)),
                ('hrct_taken', models.CharField(max_length=3, null=True)),
                ('lab_name_with_address', models.TextField(null=True)),
                ('date_of_test', models.DateField(null=True)),
                ('positive_or_negative', models.CharField(max_length=10, null=True)),
                ('sr_id', models.CharField(max_length=50, null=True)),
                ('icmr_id', models.CharField(max_length=50, null=True)),
                ('ct_thorax_taken', models.CharField(max_length=3, null=True)),
                ('ct_thorax_date', models.DateField(null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientModule.patientdetails')),
            ],
        ),
    ]
