# Generated by Django 3.2.2 on 2021-05-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0008_auto_20210508_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='ct_thorax_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='ct_thorax_taken',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='date_of_test',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='hrct_taken',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='icmr_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='lab_name_with_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='positive_or_negative',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='sr_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='swab_taken',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='RT_PCR_Details',
        ),
    ]
