# Generated by Django 3.2.2 on 2021-05-08 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0009_auto_20210508_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCaseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fever', models.BooleanField(default=False)),
                ('fever_date', models.DateField(default=datetime.date.today)),
                ('cough', models.BooleanField(default=False)),
                ('cough_date', models.DateField(default=datetime.date.today)),
                ('throat_pain', models.BooleanField(default=False)),
                ('throat_pain_date', models.DateField(default=datetime.date.today)),
                ('breathlessness', models.BooleanField(default=False)),
                ('breathlessness_date', models.DateField(default=datetime.date.today)),
                ('loose_stool', models.BooleanField(default=False)),
                ('loose_stool_date', models.DateField(default=datetime.date.today)),
                ('body_pain', models.BooleanField(default=False)),
                ('body_pain_date', models.DateField(default=datetime.date.today)),
                ('loss_smell', models.BooleanField(default=False)),
                ('loss_smell_date', models.DateField(default=datetime.date.today)),
                ('loss_of_taste', models.BooleanField(default=False)),
                ('loss_of_taste_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
