# Generated by Django 3.2.2 on 2021-05-08 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0010_patientcasesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcasesheet',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PatientModule.patientdetails'),
        ),
    ]
