# Generated by Django 3.2.2 on 2021-05-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0011_patientcasesheet_patient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientCaseSheet',
            new_name='Symptoms',
        ),
    ]
