# Generated by Django 3.2.2 on 2021-05-08 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0012_rename_patientcasesheet_symptoms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_rate', models.CharField(max_length=20, null=True)),
                ('blood_pressure', models.CharField(max_length=20, null=True)),
                ('respiratory_rate', models.CharField(max_length=20, null=True)),
                ('spo2', models.CharField(max_length=20, null=True)),
                ('temperature', models.CharField(max_length=20, null=True)),
                ('cbg', models.CharField(max_length=20, null=True)),
                ('co2', models.CharField(max_length=20, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientModule.patientdetails')),
            ],
        ),
    ]
