# Generated by Django 3.2.2 on 2021-05-08 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0013_signs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signs',
            name='co2',
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='body_pain_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='breathlessness_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='cough_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='fever_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='loose_stool_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='loss_of_taste_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='loss_smell_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='throat_pain_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='PastHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systematic_hypertension', models.BooleanField(default=False)),
                ('systematic_hypertension_year', models.CharField(max_length=4, null=True)),
                ('systematic_hypertension_treatment', models.CharField(max_length=20, null=True)),
                ('diabetes_mellitess', models.BooleanField(default=False)),
                ('diabetes_mellitess_year', models.CharField(max_length=4, null=True)),
                ('diabetes_mellitess_treatment', models.CharField(max_length=20, null=True)),
                ('bronchial_asthma', models.BooleanField(default=False)),
                ('bronchial_asthma_year', models.CharField(max_length=4, null=True)),
                ('bronchial_asthma_treatment', models.CharField(max_length=20, null=True)),
                ('chronic_kidney_disease', models.BooleanField(default=False)),
                ('chronic_kidney_disease_year', models.CharField(max_length=4, null=True)),
                ('chronic_kidney_disease_treatment', models.CharField(max_length=20, null=True)),
                ('copd', models.BooleanField(default=False)),
                ('copd_year', models.CharField(max_length=4, null=True)),
                ('copd_treatment', models.CharField(max_length=20, null=True)),
                ('hiv', models.BooleanField(default=False)),
                ('hiv_year', models.CharField(max_length=4, null=True)),
                ('hiv_treatment', models.CharField(max_length=20, null=True)),
                ('hepatitis_b', models.BooleanField(default=False)),
                ('hepatitis_b_year', models.CharField(max_length=4, null=True)),
                ('hepatitis_b_treatment', models.CharField(max_length=20, null=True)),
                ('hepatitis_c', models.BooleanField(default=False)),
                ('hepatitis_c_year', models.CharField(max_length=4, null=True)),
                ('hepatitis_c_treatment', models.CharField(max_length=20, null=True)),
                ('abdominal_pain', models.BooleanField(default=False)),
                ('abdominal_pain_year', models.CharField(max_length=4, null=True)),
                ('abdominal_pain_treatment', models.CharField(max_length=20, null=True)),
                ('diarrhea', models.BooleanField(default=False)),
                ('diarrhea_year', models.CharField(max_length=4, null=True)),
                ('diarrhea_treatment', models.CharField(max_length=20, null=True)),
                ('jaundice', models.BooleanField(default=False)),
                ('jaundice_year', models.CharField(max_length=4, null=True)),
                ('jaundice_treatment', models.CharField(max_length=20, null=True)),
                ('malignancy', models.BooleanField(default=False)),
                ('malignancy_year', models.CharField(max_length=4, null=True)),
                ('malignancy_treatment', models.CharField(max_length=20, null=True)),
                ('past_history', models.BooleanField(default=False)),
                ('past_history_year', models.CharField(max_length=4, null=True)),
                ('past_history_treatment', models.CharField(max_length=20, null=True)),
                ('other_person_history', models.BooleanField(default=False)),
                ('other_person_year', models.CharField(max_length=4, null=True)),
                ('other_person_treatment', models.CharField(max_length=20, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientModule.patientdetails')),
            ],
        ),
    ]
