# Generated by Django 3.2.2 on 2021-05-09 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0014_auto_20210508_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='body_pain_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='breathlessness_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='cough_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='fever_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='loose_stool_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='loss_of_taste_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='loss_smell_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symptoms',
            name='throat_pain_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
