# Generated by Django 3.2.2 on 2021-05-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0015_auto_20210509_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasthistory',
            name='abdominal_pain_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='bronchial_asthma_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='chronic_kidney_disease_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='copd_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='diabetes_mellitess_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='diarrhea_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='hepatitis_b_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='hepatitis_c_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='hiv_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='jaundice_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='malignancy_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='other_person_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='past_history_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='systematic_hypertension_treatment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='ct_thorax_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='ct_thorax_taken',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='date_of_test',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='hrct_taken',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='icmr_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='lab_name_with_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='positive_or_negative',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='sr_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='swab_taken',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
