# Generated by Django 3.2.2 on 2021-05-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0016_auto_20210509_0229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallor', models.BooleanField(blank=True, null=True)),
                ('ictcrus', models.BooleanField(blank=True, null=True)),
                ('cyanosis', models.BooleanField(blank=True, null=True)),
                ('clubbing', models.BooleanField(blank=True, null=True)),
                ('lymphadenpathy', models.BooleanField(blank=True, null=True)),
                ('edema', models.BooleanField(blank=True, null=True)),
                ('respiratory_system', models.CharField(max_length=10, null=True)),
                ('respiratory_normal', models.CharField(max_length=30, null=True)),
                ('respiratory_abnormal', models.CharField(max_length=30, null=True)),
                ('cardiovascular_system', models.CharField(max_length=10, null=True)),
                ('cardiovascular_normal', models.CharField(max_length=30, null=True)),
                ('cardiovascular_abnormal', models.CharField(max_length=30, null=True)),
                ('gastrointestinal', models.CharField(max_length=10, null=True)),
                ('gastrointestinal_normal', models.CharField(max_length=30, null=True)),
                ('gastrointestinal_abnormal', models.CharField(max_length=30, null=True)),
                ('cns', models.CharField(max_length=10, null=True)),
                ('cns_normal', models.CharField(max_length=30, null=True)),
                ('cns_abnormal', models.CharField(max_length=30, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientModule.patientdetails')),
            ],
        ),
    ]
