# Generated by Django 3.2.2 on 2021-05-09 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0018_auto_20210509_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='differentialdiagnosis',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PatientModule.patientdetails'),
        ),
        migrations.CreateModel(
            name='HealthFacalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facalitiedvisited', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(null=True)),
                ('treatment', models.CharField(max_length=80, null=True)),
                ('remarks', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PatientModule.patientdetails')),
            ],
        ),
    ]
