# Generated by Django 3.2.2 on 2021-05-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0019_auto_20210509_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='differentialdiagnosis',
            name='other',
            field=models.BooleanField(default=False),
        ),
    ]
