# Generated by Django 3.2.2 on 2021-05-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0020_differentialdiagnosis_other'),
    ]

    operations = [
        migrations.RenameField(
            model_name='differentialdiagnosis',
            old_name='other',
            new_name='others',
        ),
    ]
