# Generated by Django 3.2.2 on 2021-05-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0022_microbiology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o2', models.IntegerField()),
                ('nasalcannula', models.BooleanField(default=False)),
                ('hudson_mask', models.BooleanField(default=False)),
                ('nrbm', models.BooleanField(default=False)),
                ('niv', models.BooleanField(default=False)),
                ('niv_f102', models.BooleanField(default=False)),
                ('niv_peep', models.BooleanField(default=False)),
                ('niv_rr', models.BooleanField(default=False)),
                ('niv_ps', models.BooleanField(default=False)),
                ('inj_remdesivir', models.BooleanField(default=False)),
                ('tab_favipiravir', models.BooleanField(default=False)),
                ('inj_lmwh', models.BooleanField(default=False)),
                ('inj_lmwh_40mg', models.BooleanField(default=False)),
                ('inj_lmwh_40mg_od_bd', models.BooleanField(default=False)),
                ('inj_lmwh_60mg', models.BooleanField(default=False)),
                ('inj_lmwh_60mg_od_bd', models.BooleanField(default=False)),
                ('inj_dexamethaxone', models.BooleanField(default=False)),
                ('inj_dexamethaxone_40mg', models.BooleanField(default=False)),
                ('inj_dexamethaxone_40mg_odbd', models.BooleanField(default=False)),
                ('pantaprozole_40mg', models.BooleanField(default=False)),
                ('pantaprozole_40mg_bd', models.BooleanField(default=False)),
                ('emeset_4g', models.BooleanField(default=False)),
                ('emeset_4g_tds', models.BooleanField(default=False)),
                ('inj_ulinastatin', models.BooleanField(default=False)),
                ('inj_ulinastatin_bd', models.BooleanField(default=False)),
                ('inj_ulinastatin_tds', models.BooleanField(default=False)),
                ('t_pirfenidone_200mg', models.BooleanField(default=False)),
                ('t_pirfenidone_200mg_bd', models.BooleanField(default=False)),
                ('t_vitaminc_500mg', models.BooleanField(default=False)),
                ('t_vitaminc_500mg_tds', models.BooleanField(default=False)),
                ('t_zincovit_40mg', models.BooleanField(default=False)),
                ('t_zincovit_40mg_od', models.BooleanField(default=False)),
                ('t_nac_600mg', models.BooleanField(default=False)),
                ('t_nac_600mg_bd', models.BooleanField(default=False)),
                ('nebulisation', models.BooleanField(default=False)),
                ('prone_ventilation', models.BooleanField(default=False)),
                ('spirometer_excercise', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientModule.patientdetails')),
            ],
        ),
    ]
