# Generated by Django 3.2.2 on 2021-05-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0024_auto_20210509_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='emeset_4g',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='emeset_4g_tds',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='hudson_mask',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_dexamethaxone',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_dexamethaxone_40mg',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_dexamethaxone_40mg_odbd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_lmwh',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_lmwh_40mg',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_lmwh_40mg_od_bd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_lmwh_60mg',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_lmwh_60mg_od_bd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_remdesivir',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_ulinastatin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_ulinastatin_bd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='inj_ulinastatin_tds',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nasalcannula',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nebulisation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nebulisation_budocort',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nebulisation_budocort_qh',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nebulisation_duolin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nebulisation_duolin_qh',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='niv',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='niv_f102',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='niv_peep',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='niv_ps',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='niv_rr',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nrbm',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='pantaprozole_40mg',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='pantaprozole_40mg_bd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='prone_ventilation',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='spirometer_excercise',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='t_nac_600mg',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='t_nac_600mg_bd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='t_pirfenidone_200mg',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='t_pirfenidone_200mg_bd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='t_vitaminc_500mg',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='t_vitaminc_500mg_tds',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='t_zincovit_40mg',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='t_zincovit_40mg_od',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='tab_favipiravir',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
