# Generated by Django 3.2.2 on 2021-05-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0025_auto_20210509_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetails',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nebulisation_budocort_qh',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nebulisation_duolin_qh',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
