# Generated by Django 3.2.2 on 2021-05-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0026_auto_20210509_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='criticallity',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
