# Generated by Django 3.2.2 on 2021-05-10 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PatientModule', '0027_alter_patientdetails_criticallity'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
