# Generated by Django 3.2.2 on 2021-05-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0028_patientdetails_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='cardiovascular_abnormal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='cardiovascular_normal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='cardiovascular_system',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='cns',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='cns_abnormal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='cns_normal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='gastrointestinal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='gastrointestinal_abnormal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='gastrointestinal_normal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='respiratory_abnormal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='respiratory_normal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='respiratory_system',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacalities',
            name='Facalitiedvisited',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacalities',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthfacalities',
            name='treatment',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='rapid_anti_body_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='rt_pcr_H1N_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='rt_pcr_H1N_result',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='rt_pcr_covid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='rt_pcr_covid_result',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='viral_culture_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='viral_culture_date2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='viral_culture_result',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='microbiology',
            name='viral_culture_result2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='abdominal_pain_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='copd_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='diabetes_mellitess_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='diarrhea_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='hepatitis_b_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='hepatitis_c_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='hiv_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='jaundice_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='malignancy_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='other_person_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='past_history_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='systematic_hypertension_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='cbg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='pulse_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='respiratory_rate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='spo2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='signs',
            name='temperature',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
