# Generated by Django 3.2.2 on 2021-05-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0029_auto_20210510_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasthistory',
            name='bronchial_asthma_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pasthistory',
            name='chronic_kidney_disease_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nebulisation_budocort_qh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='nebulisation_duolin_qh',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='o2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
