# Generated by Django 3.2.2 on 2021-05-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0031_beds'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalBeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(max_length=20, null=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Beds',
        ),
        migrations.AddField(
            model_name='availablebeds',
            name='availableBed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientModule.totalbeds'),
        ),
    ]
