# Generated by Django 3.2.2 on 2021-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0032_auto_20210510_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='totalbeds',
            old_name='bed',
            new_name='hfnc',
        ),
        migrations.RemoveField(
            model_name='totalbeds',
            name='count',
        ),
        migrations.AddField(
            model_name='totalbeds',
            name='hfncCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='totalbeds',
            name='oxygen',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='totalbeds',
            name='oxygenCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='totalbeds',
            name='total',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='totalbeds',
            name='totalCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='totalbeds',
            name='ventilator',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='totalbeds',
            name='ventilatorCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='totalbeds',
            name='ward',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='totalbeds',
            name='wardCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='availablebeds',
            name='availableCount',
            field=models.IntegerField(null=True),
        ),
    ]
