# Generated by Django 3.2.2 on 2021-05-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0033_auto_20210510_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='availablebeds',
            name='availableBed',
        ),
        migrations.RemoveField(
            model_name='availablebeds',
            name='availableCount',
        ),
        migrations.DeleteModel(
            name='TotalBeds',
        ),
    ]
