# Generated by Django 3.2.2 on 2021-05-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0034_auto_20210510_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='bedCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PatientModule.beds')),
            ],
        ),
        migrations.DeleteModel(
            name='AvailableBeds',
        ),
    ]
