# Generated by Django 3.2.2 on 2021-05-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0035_auto_20210510_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='bed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PatientModule.beds'),
        ),
    ]
