# Generated by Django 3.2.2 on 2021-05-11 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0037_auto_20210510_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PatientModule.beds'),
        ),
    ]
