# Generated by Django 3.2.2 on 2021-05-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientModule', '0038_alter_patientdetails_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='expired',
            field=models.BooleanField(null=True),
        ),
    ]
